### ISSUE TITLE
cannot import Binoculars.

### ISSUE THREAD

**Issue by Dead-Bytes** [ahans30/Binoculars#11]
binoculars has no module named Binoculars. 
specifically after installing binoculars as per given instructions,
```python
 from binoculars import Binoculars
 ```
this line throws error as binoculars has no module named Binoculars

**Comment by AlbertRoh** [comment]
I am having the same problem.

**Comment by ahans30** [comment]
Sorry about that, please use `from binoculars.detector import Binoculars` and it should work. Closing this issue now, feel free to open.
