### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by TikoyX** [ahans30/Binoculars#14]
Requirements.txt is missing packages like torch and transformers

**Comment by ahans30** [comment]
[They](https://github.com/ahans30/Binoculars/blob/c8ae2f90d50ee696418bc71d8d9e5020e5f9d7b8/requirements.txt#L2) are part of `requirements.txt`

**Comment by TikoyX** [comment]
Hmmm, true that they are (it was a long day yesterday). None of them were properly installed here when using the `pip install -e .` 
You could also mention that Rust is needed
