### ISSUE TITLE
Link to Evaluation Datasets

### ISSUE THREAD

**Issue by dadamson** [ahans30/Binoculars#2]
While the Ghostbuster and Open Orca datasets are available, it would be great to be able replicate your results, or use them as a benchmark, with the Falcon/Llama examples you generated from CCNews, PubMed, and CNN data. Please share this data if you can!

**Comment by ahans30** [comment]
Thanks for raising this. I will be putting up our datasets shortly. :)

**Comment by lilakk** [comment]
Yes it would be really helpful if you could release the outputs!

**Comment by ahans30** [comment]
Hi, sorry for the delay. I have pushed the datasets. You can find them [Binoculars /datasets/](https://github.com/ahans30/Binoculars/tree/main/datasets).
