### ISSUE TITLE
Threshold tuning

### ISSUE THREAD

**Issue by zaxtax** [ahans30/Binoculars#3]
Would you be able to put up the code you used to tune the threshold for the classifier? The value is highly sensitive to the choice of performer and observer model

**Comment by ahans30** [comment]
You can use following to get set of thresholds for different false positive rates and true positive rates. Hope this helps.

`fpr, tpr, thresholds = metrics.roc_curve(y_true=score_df["class"], y_score=score, pos_label=1)`

Further, you can interpolate threshold for desired pair of tpr/fpr.
