### ISSUE TITLE
fpr threshold 

### ISSUE THREAD

**Issue by nivancat** [ahans30/Binoculars#7]
What does BINOCULARS_FPR_THRESHOLD of 0.8536432310785527 correspond to? Is that 1% or 0.01% in the paper?

**Comment by ahans30** [comment]
Thanks for your interest. It's 0.01%.

**Comment by nivancat** [comment]
thank you!

**Comment by nivancat** [comment]
Is there any chance you could share the 1% threshold value, am trying to compare? I cant seem to recalibrate for with the M4 to land on the same value
