### ISSUE TITLE
Figure 7

### ISSUE THREAD

**Issue by nivancat** [ahans30/Binoculars#8]
Many thanks for the paper, I am struggling a bit with Fig 7.

How come false negatives are so high? Where are the generated russian urdu etc samples coming from?

**Comment by ahans30** [comment]
Hi, thanks for your interest! 

Binoculars' effectiveness is dependent on the next-token-prediction ability of models powering it.  In this case (i.e. experiments in paper), the Falcon model family is not a great choice with Russian, Urdu, and other low-resource languages text. The false negative could be alleviated by using a better pair of multi-lingual models. We used the M4 dataset released with [https://arxiv.org/abs/2305.14902](https://arxiv.org/abs/2305.14902) for these samples. 

Hope this helps!

**Comment by nivancat** [comment]
Sorry, no that is not what I meant. The eval for Fig 7 appears to be very disbalanced, so I was just wondering what dataset was used to generate it? Is this russian text coming from CC?

**Comment by nivancat** [comment]
thank you

**Comment by nivancat** [comment]
How did the number end up being 1-2% then? Where are the negatives coming from?
